# Generated by Django 5.1 on 2026-05-13 20:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('f2_done_at', models.DateTimeField(blank=True, null=True)),
                ('sp01_done_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('origin_code', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hu_code', models.CharField(max_length=50)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='HUItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hu_code', models.CharField(max_length=50, unique=True)),
                ('origin_code', models.CharField(blank=True, default='', max_length=20)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando...'), ('ok', 'OK'), ('duplicate', 'Ya procesado'), ('error', 'Error'), ('hu_not_found', 'HU no existe')], default='pending', max_length=20)),
                ('phase1_msg', models.CharField(blank=True, default='', max_length=255)),
                ('phase2_msg', models.CharField(blank=True, default='', max_length=255)),
                ('phase2_ms', models.IntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('f1_done_at', models.DateTimeField(blank=True, null=True)),
                ('sp01_done_at', models.DateTimeField(blank=True, null=True)),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='queue_app.pallet')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
    ]
